### ISSUE TITLE
BCM94352Z kexts

### ISSUE THREAD

**Issue by ginaldoterencio** [h-okon/Acer-Aspire-A515-Hackintosh#3]
Hi! Thanks for sharing your EFI!
Can you tell me pls which kexts and kext patches are asociateds with BCM94352Z(DW1560?

**Comment by h-okon** [comment]
kexts/other/BrcmFirmwareRepo.kext
kexts/other/FakePCIID.kext
kexts/other/FakePCIID_Broadcom_WiFi.kext
kexts/other/BrcmPatchRAM2.kext
+ in config.plist remove those patches (through Clover Configurator) :
[those](http://prntscr.com/ogad1j)

**Comment by ginaldoterencio** [comment]
Thanks a lot! :)
